sudo: required

language: minimal

script:
  - echo "npm test temporarily disabled"

install:
  - echo "npm test temporarily disabled"

deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: files.dmm.exchange
    skip_cleanup: true
    local-dir: files
    cache_control: "public, max-age=900"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$
